services:
    _instanceof:
        Oro\Component\MessageQueue\Client\TopicSubscriberInterface:
            tags:
                - { name: oro_message_queue.client.message_processor }

    oro_dotmailer.async.export_contacts_status_update_processor:
        class: Oro\Bundle\DotmailerBundle\Async\ExportContactsStatusUpdateProcessor
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_dotmailer.export_manager'
            - '@oro_dotmailer.queue_export_manager'
            - '@oro_message_queue.job.runner'
            - '@security.token_storage'
            - '@logger'
            - '@oro_message_queue.job.processor'
