datagrids:
    oro_dotmailer_address_books_grid:
        extended_entity_name: 'Oro\Bundle\DotmailerBundle\Entity\AddressBook'
        channel_limitation:
            channel_relation_path: .channel
        options:
            entityHint: oro.dotmailer.addressbook.datagrid.entity_hint
        source:
            type: orm
            query:
                select:
                    - addressBook.id
                    - addressBook.name
                    - addressBook.contactCount
                from:
                    - { table: 'Oro\Bundle\DotmailerBundle\Entity\AddressBook', alias: addressBook }
                join:
                    left:
                        - { join: addressBook.visibility, alias: address_book_visibility }
                where:
                    and:
                        - addressBook.marketingList IS NULL
                        - addressBook.owner = @oro_security.token_accessor->getOrganizationId
        columns:
            name:
                label: oro.dotmailer.addressbook.name.label
            contactCount:
                label: oro.dotmailer.addressbook.contact_count.label
        sorters:
            columns:
                name:
                    data_name: addressBook.name
                contactCount:
                    data_name: addressBook.contactCount
            default:
                name: ASC
        filters:
            columns:
                name:
                    type: string
                    data_name: addressBook.name
                contactCount:
                    type: string
                    data_name: addressBook.contactCount
        properties:
            id: ~

    oro_dotmailer_datafield_grid:
        extended_entity_name: 'Oro\Bundle\DotmailerBundle\Entity\DataField'
        channel_limitation:
            channel_relation_path: .channel
        options:
            entityHint: oro.dotmailer.datafield.entity_plural_label
        source:
            type: orm
            query:
                select:
                    - field.id
                    - field.name
                    - field.notes
                    - channel.name as channelName
                from:
                    - { table: 'Oro\Bundle\DotmailerBundle\Entity\DataField', alias: field }
                join:
                    left:
                        - { join: field.channel, alias: channel }
        inline_editing:
            enable: true
            behaviour: enable_selected
        columns:
            channelName:
                label: oro.dotmailer.datafield.channel.label
            name:
                label: oro.dotmailer.datafield.name.label
            notes:
                label: oro.dotmailer.datafield.notes.label
                inline_editing:
                    enable: true
                    editor:
                        view: oroform/js/app/views/editor/text-editor-view
        sorters:
            columns:
                name:
                    data_name: field.name
                channelName:
                    data_name: channel.name
            default:
                name: ASC
        filters:
            columns:
                channelName:
                    type: entity
                    data_name: channel.id
                    options:
                        field_options:
                            class: Oro\Bundle\IntegrationBundle\Entity\Channel
                            choice_label: name
                            translatable_options: false
                name:
                    type: string
                    data_name: field.name
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_dotmailer_datafield_view
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_dotmailer_datafield
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  oro_dotmailer_datafield_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
            delete:
                type:          delete
                acl_resource:  oro_dotmailer_datafield_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link

    oro_dotmailer_datafield_mapping_grid:
        extended_entity_name: 'Oro\Bundle\DotmailerBundle\Entity\DataFieldMapping'
        options:
            entityHint: oro.dotmailer.datafieldmapping.entity_plural_label
        source:
            type: orm
            query:
                select:
                    - mapping.id
                    - mapping.entity
                    - mapping.syncPriority
                    - channel.name as channelName
                from:
                    - { table: 'Oro\Bundle\DotmailerBundle\Entity\DataFieldMapping', alias: mapping }
                join:
                    left:
                        - { join: mapping.channel, alias: channel }
        columns:
            channelName:
                label: oro.dotmailer.datafieldmapping.channel.label
            entity:
                label: oro.dotmailer.datafieldmapping.entity.label
                type: twig
                template: '@OroEntity/Datagrid/Property/entity.html.twig'
                frontend_type: html
                context:
                    entity_provider: "@oro_dotmailer.entity_provider"
            syncPriority:
                label: oro.dotmailer.datafieldmapping.sync_priority.label
        sorters:
            columns:
                entity:
                    data_name: mapping.entity
                channelName:
                    data_name: channel.name
                syncPriority:
                    data_name: mapping.syncPriority
            default:
                entity: ASC
        filters:
            columns:
                channelName:
                    type: entity
                    data_name: channel.id
                    options:
                        field_options:
                            class: Oro\Bundle\IntegrationBundle\Entity\Channel
                            choice_label: name
                            translatable_options: false
                entity:
                    type: string
                    data_name: mapping.entity
        properties:
            id: ~
            update_link:
                type:       url
                route:      oro_dotmailer_datafield_mapping_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_dotmailer_datafield_mapping
                params:     [ id ]
        actions:
            update:
                type:          navigate
                acl_resource:  oro_dotmailer_datafield_mapping_update
                label:         oro.grid.action.view
                icon:          edit
                link:          update_link
                rowAction:     true
            delete:
                type:          delete
                acl_resource:  oro_dotmailer_datafield_mapping_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link
