navigation:
    menu_config:
        items:
            oro_dotmailer:
                label: 'oro.dotmailer.channel_type.label'
                uri: '#'
                linkAttributes:
                    class: 'dotmailer'
                position: 50
            oro_dotmailer_data_field_list:
                label: 'oro.dotmailer.datafield.entity_plural_label'
                route: 'oro_dotmailer_datafield_index'
                extras:
                    routes: ['/^oro_dotmailer_datafield_(?!mapping\w+)\w+$/']
            oro_dotmailer_data_field_mapping_list:
                label: 'oro.dotmailer.datafieldmapping.entity_plural_label'
                route: 'oro_dotmailer_datafield_mapping_index'
                extras:
                    routes: ['oro_dotmailer_datafield_mapping_*']
            oro_dotmailer_integration_connection:
                label: 'oro.dotmailer.integration.connection.label'
                route: 'oro_dotmailer_integration_connection'
                position: 10
                extras:
                    routes: ['oro_dotmailer_integration_connection']

        tree:
            application_menu:
                children:
                    marketing_tab:
                        children:
                          oro_dotmailer:
                              children:
                                  oro_dotmailer_integration_connection: ~
                                  oro_dotmailer_data_field_list: ~
                                  oro_dotmailer_data_field_mapping_list: ~

    titles:
        oro_dotmailer_datafield_index: ~
        oro_dotmailer_datafield_create: 'Add dotdigital Data Field'
        oro_dotmailer_datafield_view: '%datafield.name%'

        oro_dotmailer_datafield_mapping_index: ~
        oro_dotmailer_datafield_mapping_create: 'Add dotdigital Data Field Mapping'
        oro_dotmailer_datafield_mapping_update: 'Update dotdigital Data Field Mapping'

        oro_dotmailer_integration_connection: '%title%'
