placeholders:
    placeholders:
        view_navButtons_before:
            items:
                oro_dotmailer_marketing_list_buttons: ~
        view_content_data_email_campaign_status:
            items:
                oro_dotmailer_emailcampaign_stats: ~
        marketing_list_sync_info:
            items:
                oro_dotmailer_marketing_list_sync_data: ~

    items:
        oro_dotmailer_marketing_list_buttons:
            acl: [oro_marketing_list_update, oro_dotmailer_address_book_update]
            action: Oro\Bundle\DotmailerBundle\Controller\AddressBookController::connectionButtonsAction
            applicable: "@oro_dotmailer.placeholder.filter.buttons_filter->isApplicable($entity$)"

        oro_dotmailer_emailcampaign_stats:
            acl: oro_email_campaign_view
            action: Oro\Bundle\DotmailerBundle\Controller\DotmailerController::emailCampaignStatsAction
            applicable: "@oro_dotmailer.placeholder.filter.email_campaign->isApplicableOnEmailCampaign($entity$)"

        oro_dotmailer_marketing_list_sync_data:
            acl: oro_marketing_list_view
            action: Oro\Bundle\DotmailerBundle\Controller\DotmailerController::marketingListSyncStatusAction
            applicable: "@oro_dotmailer.placeholder.filter.sync_status->isApplicableOnMarketingList($marketingList$)"
